# -*- coding: utf-8 -*-
"""Mall Customers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVwMT1KmbP1hgJJ0c8aqrQNwLcZ0Oaru
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_excel('Mall Customers.xlsx')

df.head(100)

df.isnull().sum()

df.columns

df.describe()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.countplot(x='Gender', data=df)
plt.show()

sns.histplot(df['Age'], kde=True)
plt.show()

sns.histplot(df['Annual Income (k$)'], kde=True)
plt.show()

sns.histplot(df['Spending Score (1-100)'], kde=True)
plt.show()

X = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.cluster import KMeans

wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

df.head()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_data = pca.fit_transform(X_scaled)

df['PCA1'] = pca_data[:, 0]
df['PCA2'] = pca_data[:, 1]
sns.scatterplot(
    x='PCA1', y='PCA2',
    hue='Cluster',
    palette='Set1',
    data=df
)
plt.title('Customer Segments using PCA')
plt.show()

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42, perplexity=30)
tsne_data = tsne.fit_transform(X_scaled)

df['TSNE1'] = tsne_data[:, 0]
df['TSNE2'] = tsne_data[:, 1]
sns.scatterplot(
    x='TSNE1', y='TSNE2',
    hue='Cluster',
    palette='Set2',
    data=df
)
plt.title('Customer Segments using t-SNE')
plt.show()

df.groupby('Cluster')[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']].mean()